"use client"

import React, { createContext, useContext, useState, ReactNode, useEffect } from "react"

export type Language = "es" | "en"

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const translations = {
    es: {
        // Common
        "common.dashboard": "Dashboard",
        "common.settings": "Configuración",
        "common.profile": "Perfil",
        "common.logout": "Cerrar Sesión",
        "common.notifications": "Notificaciones",
        "common.welcome": "¡Bienvenido de vuelta!",
        "common.loading": "Cargando...",
        "common.save": "Guardar",
        "common.cancel": "Cancelar",
        "common.view_details": "Ver Detalles",
        "common.close": "Cerrar",
        "common.my_account": "Mi Cuenta",
        "common.app_name": "Sistema CUBOT",
        "common.error.imei_not_found": "IMEI no encontrado en el inventario",
        "common.error.imei_verification": "Error al verificar IMEI",
        "common.error.upload_evidence": "La evidencia de venta es requerida",
        "common.error.generic": "Error inesperado",

        // Vendor Sidebar
        "vendor.nav.dashboard": "Dashboard",
        "vendor.nav.register_sale": "Registrar Venta",
        "vendor.nav.my_sales": "Mis Ventas",
        "vendor.nav.commissions": "Comisiones",
        "vendor.nav.payments": "Pagos",
        "vendor.nav.products": "Productos",
        "vendor.nav.profile": "Perfil",
        "vendor.nav.notifications": "Notificaciones",

        // Admin Sidebar
        "admin.nav.dashboard": "Dashboard",
        "admin.nav.users": "Usuarios",
        "admin.nav.products": "Productos",
        "admin.nav.banks": "Bancos",
        "admin.nav.sales": "Ventas",
        "admin.nav.validation": "Cola de Validación",
        "admin.nav.commissions": "Comisiones",
        "admin.nav.payments": "Pagos",
        "admin.nav.reports": "Reportes",
        "admin.nav.notifications": "Notificaciones",
        "admin.nav.configuration": "Configuración",

        // Vendor Dashboard
        "vendor.hero.subtitle": "Aquí está tu resumen de ventas y comisiones",
        "vendor.stats.total_sales": "Total de Ventas",
        "vendor.stats.validation": "En Validación",
        "vendor.stats.month_sales": "Ventas del Mes",
        "vendor.stats.total_earned": "Total Ganado",
        "vendor.stats.pending_commissions": "Comisiones Pendientes",
        "vendor.stats.paid_commissions": "Comisiones Pagadas",

        "vendor.actions.new_sale.title": "Registrar Nueva Venta",
        "vendor.actions.new_sale.desc": "Completa el formulario para registrar una nueva venta de equipo CUBOT",
        "vendor.actions.new_sale.btn": "Crear Venta",

        "vendor.actions.commissions.title": "Mis Comisiones",
        "vendor.actions.commissions.desc": "Revisa el estado de tus comisiones y pagos realizados",
        "vendor.actions.commissions.btn": "Ver Comisiones",

        // Sale Form
        "vendor.sales.new.page_title": "Registrar Nueva Venta",
        "vendor.sales.new.subtitle": "Registrar una nueva venta con verificación de IMEI",
        "vendor.sales.new.imei_label": "IMEI (15 dígitos)",
        "vendor.sales.new.verifying": "Verificando...",
        "vendor.sales.new.imei_verified": "IMEI verificado",
        "vendor.sales.new.model": "Modelo",
        "vendor.sales.new.status": "Estado",
        "vendor.sales.new.product_label": "Producto",
        "vendor.sales.new.product_not_found_warning": "Nota: El producto verificado ({model}) no existe en el catálogo actual.",
        "vendor.sales.new.select_product": "Seleccione un producto",
        "vendor.sales.new.channel_label": "Canal de Venta",
        "vendor.sales.new.channel.online": "Online",
        "vendor.sales.new.channel.store": "Tienda Física",
        "vendor.sales.new.channel.marketplace": "Marketplace",
        "vendor.sales.new.channel.phone": "Venta Telefónica",
        "vendor.sales.new.date_label": "Fecha de Venta",
        "vendor.sales.new.notes_label": "Notas (Opcional)",
        "vendor.sales.new.evidence_label": "Evidencia (Foto/PDF)",
        "vendor.sales.new.evidence_hint": "JPG, PNG o PDF. Max 5MB.",
        "vendor.sales.new.submit_btn": "Registrar Venta",
        "vendor.sales.new.submitting": "Registrando...",

        // Vendor Commissions
        "vendor.commissions.title": "Mis Comisiones",
        "vendor.commissions.subtitle": "Rastrea tus ganancias y estado de comisiones",
        "vendor.commissions.pending": "Comisiones Pendientes",
        "vendor.commissions.paid": "Comisiones Pagadas",
        "vendor.commissions.table.sale_id": "ID Venta",
        "vendor.commissions.table.product": "Producto",
        "vendor.commissions.table.base_amount": "Monto Base",
        "vendor.commissions.table.commission": "Comisión",
        "vendor.commissions.table.status": "Estado",
        "vendor.commissions.table.date": "Fecha",
        "vendor.commissions.empty.title": "Aún no hay comisiones",
        "vendor.commissions.empty.desc": "Las comisiones aparecerán aquí después de que las ventas sean aprobadas",

        // Vendor Payments
        "vendor.payments.title": "Historial de Pagos",
        "vendor.payments.subtitle": "Visualiza tus lotes de pago e historial de transacciones",
        "vendor.payments.table.batch_id": "ID Lote",
        "vendor.payments.table.commissions": "Comisiones",
        "vendor.payments.table.amount": "Monto",
        "vendor.payments.table.status": "Estado",
        "vendor.payments.table.date": "Fecha",
        "vendor.payments.empty.title": "Aún no hay historial de pagos",
        "vendor.payments.empty.desc": "Los lotes de pago aparecerán aquí una vez procesados",

        // Vendor Products
        "vendor.products.title": "Catálogo de Productos",
        "vendor.products.subtitle": "Explora los productos disponibles y sus comisiones",
        "vendor.products.active": "Activo",
        "vendor.products.price": "Precio",
        "vendor.products.price_tooltip": "Precio de venta del producto",
        "vendor.products.your_commission": "Tu Comisión",
        "vendor.products.commission_fixed": "Comisión fija por venta",
        "vendor.products.commission_percent": "Comisión del {percent}% sobre el precio de venta",
        "vendor.products.commission_none": "Sin comisión configurada",
        "vendor.products.empty.title": "No hay productos disponibles",
        "vendor.products.empty.desc": "Contacta al administrador para agregar productos al catálogo",

        // Vendor Profile
        "vendor.profile.title": "Mi Perfil",
        "vendor.profile.subtitle": "Gestiona tu información personal y cuenta bancaria",
        "vendor.profile.details.vendor_id": "ID Vendedor",
        "vendor.profile.details.email": "Email",
        "vendor.profile.details.status": "Estado",
        "vendor.profile.details.kyc_status": "Estado KYC",
        "vendor.profile.details.id_number": "Cédula/RNC",
        "vendor.profile.status.active": "Activo",
        "vendor.profile.status.suspended": "Suspendido",
        "vendor.profile.status.approved": "Aprobado",
        "vendor.profile.status.rejected": "Rechazado",
        "vendor.profile.status.pending": "Pendiente",

        "vendor.profile.form.title": "Información Personal",
        "vendor.profile.form.desc": "Completa tu información personal para verificación",
        "vendor.profile.form.full_name": "Nombre Completo",
        "vendor.profile.form.phone": "Teléfono",
        "vendor.profile.form.country": "País",
        "vendor.profile.form.address": "Dirección",
        "vendor.profile.form.city": "Ciudad",
        "vendor.profile.form.state": "Provincia/Estado",
        "vendor.profile.form.zip": "Código Postal",
        "vendor.profile.form.save": "Guardar Cambios",
        "vendor.profile.form.saving": "Guardando...",
        "vendor.profile.form.kyc_alert": "Debes completar tu cédula de identidad o RNC para la verificación KYC.",

        // Vendor Bank Accounts
        "vendor.bank.title": "Cuentas Bancarias",
        "vendor.bank.subtitle": "Gestiona tus cuentas bancarias para recibir pagos",
        "vendor.bank.add_btn": "Agregar Cuenta Bancaria",
        "vendor.bank.form.title": "Agregar Cuenta Bancaria",
        "vendor.bank.form.desc": "Selecciona un banco e ingresa los detalles de tu cuenta",
        "vendor.bank.form.bank": "Banco",
        "vendor.bank.form.holder": "Nombre del Titular",
        "vendor.bank.form.number": "Número de Cuenta",
        "vendor.bank.form.type": "Tipo de Cuenta",
        "vendor.bank.form.primary": "Establecer como cuenta principal (usada para pagos)",
        "vendor.bank.form.save": "Guardar Cuenta",
        "vendor.bank.form.cancel": "Cancelar",
        "vendor.bank.empty.title": "No hay cuentas bancarias configuradas",
        "vendor.bank.empty.desc": "Agrega una cuenta bancaria para recibir pagos de tus comisiones",
        "vendor.bank.verified": "Verificada",
        "vendor.bank.pending": "Pendiente de Verificación",
        "vendor.bank.set_primary": "Establecer Principal",
        "vendor.bank.delete.title": "¿Eliminar cuenta bancaria?",
        "vendor.bank.delete.desc": "Esta acción no se puede deshacer. La cuenta bancaria será eliminada permanentemente de tu perfil.",
        "vendor.bank.delete.btn": "Eliminar",

        // Vendor Notifications
        "vendor.notifications.title": "Notificaciones",
        "vendor.notifications.subtitle": "{unread} no leídas de {total} totales",
        "vendor.notifications.mark_all": "Marcar todas como leídas",
        "vendor.notifications.mark_read": "Marcar leída",
        "vendor.notifications.empty": "No hay notificaciones",
        "vendor.notifications.new": "Nueva",
        "vendor.sales.list.title": "Mis Ventas",
        "vendor.sales.list.subtitle": "Visualiza y rastrea todas tus ventas",
        "vendor.sales.list.stat.total": "Total Ventas",
        "vendor.sales.list.stat.approved": "Aprobadas",
        "vendor.sales.list.stat.pending": "Pendientes",
        "vendor.sales.list.stat.revenue": "Ingresos Totales",
        "vendor.sales.list.table.id": "ID Venta",
        "vendor.sales.list.table.product": "Producto",
        "vendor.sales.list.table.client": "Cliente",
        "vendor.sales.list.table.imei": "IMEI",
        "vendor.sales.list.table.price": "Precio",
        "vendor.sales.list.table.status": "Estado",
        "vendor.sales.list.table.date": "Fecha",
        "vendor.sales.list.status.approved": "Aprobada",
        "vendor.sales.list.status.rejected": "Rechazada",
        "vendor.sales.list.status.pending": "Pendiente",
        "vendor.sales.list.empty.title": "No hay ventas registradas",
        "vendor.sales.list.empty.desc": "Comienza registrando tu primera venta desde el menú de navegación",

        // Admin - Users
        "admin.users.title": "Gestión de Usuarios",
        "admin.users.subtitle": "Administra usuarios del sistema",
        "admin.users.search_placeholder": "Buscar por nombre, email, ID de vendedor o teléfono...",
        "admin.users.tabs.all": "Todos",
        "admin.users.tabs.admins": "Admin",
        "admin.users.tabs.vendors": "Vendedores",
        "admin.users.empty_search": "No se encontraron usuarios con ese criterio",
        "admin.users.empty_all": "No hay usuarios registrados",
        "admin.users.role.admin": "Administrador",
        "admin.users.role.validator": "Validador",
        "admin.users.role.finance": "Finanzas",
        "admin.users.role.vendor": "Vendedor",
        "admin.users.status.active": "Activo",
        "admin.users.status.suspended": "Suspendido",
        "admin.users.kyc.approved": "Aprobado",
        "admin.users.kyc.rejected": "Rechazado",
        "admin.users.kyc.pending": "Pendiente",
        "admin.users.actions.edit": "Editar",
        "admin.users.actions.suspend": "Suspender",
        "admin.users.actions.activate": "Activar",
        "admin.users.actions.approve": "Aprobar",
        "admin.users.actions.reject": "Rechazar",
        "admin.users.actions_label": "Acciones",
        "admin.users.dialog.reject_title": "Rechazar KYC",
        "admin.users.dialog.reject_desc": "Proporciona una razón para rechazar el KYC de {name}",
        "admin.users.dialog.reject_reason": "Razón del rechazo",
        "admin.users.dialog.reject_placeholder": "Ej: Documentos incompletos...",
        "admin.users.dialog.cancel": "Cancelar",
        "admin.users.dialog.confirm_reject": "Rechazar KYC",
        "admin.users.registered": "Registrado: {date}",
        "admin.users.loading": "Cargando usuarios...",

        // Admin - Products
        "admin.products.title": "Productos",
        "admin.products.subtitle": "Gestiona el catálogo de productos CUBOT",
        "admin.products.add_button": "Agregar Producto",
        "admin.products.edit_title": "Editar Producto",
        "admin.products.add_title": "Agregar Nuevo Producto",
        "admin.products.edit_desc": "Actualiza la información del producto",
        "admin.products.add_desc": "Agrega un nuevo producto al catálogo",
        "admin.products.form.sku": "SKU",
        "admin.products.form.sku_tooltip": "Código único del producto",
        "admin.products.form.name": "Nombre",
        "admin.products.form.category": "Categoría",
        "admin.products.form.price": "Precio (RD$)",
        "admin.products.form.price_tooltip": "Precio de venta del producto en pesos dominicanos",
        "admin.products.form.commission_label": "Comisión",
        "admin.products.form.commission_fixed": "Monto Fijo (RD$)",
        "admin.products.form.commission_fixed_tooltip": "Comisión fija por venta (dejar en 0 si usas porcentaje)",
        "admin.products.form.commission_percent": "Porcentaje (%)",
        "admin.products.form.commission_percent_tooltip": "Porcentaje de comisión sobre el precio de venta (dejar en 0 si usas monto fijo)",
        "admin.products.form.stock": "Stock",
        "admin.products.form.active": "Producto activo (visible para vendedores)",
        "admin.products.form.save_loading": "Guardando...",
        "admin.products.form.update": "Actualizar Producto",
        "admin.products.form.create": "Crear Producto",
        "admin.products.form.cancel": "Cancelar",
        "admin.products.status.active": "Activo",
        "admin.products.status.inactive": "Inactivo",
        "admin.products.card.category": "Categoría",
        "admin.products.card.price": "Precio",
        "admin.products.card.commission": "Comisión",
        "admin.products.card.commission_fixed": "Comisión fija por venta",
        "admin.products.card.commission_percent": "Comisión del {percent}% sobre el precio",
        "admin.products.card.commission_none": "Sin comisión configurada",
        "admin.products.card.stock": "Stock",
        "admin.products.card.edit_action": "Editar Producto",
        "admin.products.empty.title": "No hay productos registrados",
        "admin.products.empty.desc": "Agrega productos al catálogo para que los vendedores puedan venderlos",

        // Admin - Banks
        "admin.banks.title": "Gestión de Bancos",
        "admin.banks.subtitle": "Configura los bancos disponibles para cuentas de pago de vendedores",
        "admin.banks.add_button": "Agregar Banco",
        "admin.banks.edit_title": "Editar Banco",
        "admin.banks.add_title": "Agregar Nuevo Banco",
        "admin.banks.edit_desc": "Actualiza la información del banco",
        "admin.banks.add_desc": "Agrega un nuevo banco que los vendedores pueden usar para pagos",
        "admin.banks.form.name": "Nombre del Banco",
        "admin.banks.form.code": "Código del Banco",
        "admin.banks.form.code_tooltip": "Código único del banco (ej: BPD, BHD)",
        "admin.banks.form.country": "Código de País",
        "admin.banks.form.format": "Formato de Número de Cuenta",
        "admin.banks.form.format_tooltip": "Pista de formato para vendedores (ej: '20 dígitos')",
        "admin.banks.form.active": "Activo (visible para vendedores)",
        "admin.banks.empty.title": "No hay bancos configurados",
        "admin.banks.empty.desc": "Agrega un banco para que los vendedores puedan configurar sus cuentas bancarias",
        "admin.banks.delete_title": "¿Eliminar banco?",
        "admin.banks.delete_desc": "Esta acción no se puede deshacer. El banco será eliminado permanentemente del sistema.",
        "admin.banks.delete_confirm": "Eliminar",

        // Admin - Sales
        "admin.sales.title": "Ventas",
        "admin.sales.subtitle": "Gestiona y visualiza todas las ventas del sistema",
        "admin.sales.stats.total": "Total Ventas",
        "admin.sales.stats.approved": "Aprobadas",
        "admin.sales.stats.pending": "Pendientes",
        "admin.sales.stats.revenue": "Ingresos Totales",
        "admin.sales.table.sale_id": "ID Venta",
        "admin.sales.table.vendor": "Vendedor",
        "admin.sales.table.product": "Producto",
        "admin.sales.table.imei": "IMEI",
        "admin.sales.table.price": "Precio",
        "admin.sales.table.status": "Estado",
        "admin.sales.table.date": "Fecha",
        "admin.sales.status.approved": "Aprobada",
        "admin.sales.status.rejected": "Rechazada",
        "admin.sales.status.pending": "Pendiente",
        "admin.sales.empty.title": "No hay ventas registradas",
        "admin.sales.empty.desc": "Las ventas aparecerán aquí cuando los vendedores las registren",

        // Admin - Reports
        "admin.reports.title": "Centro de Reportes",
        "admin.reports.subtitle": "Análisis completo del rendimiento de tu negocio",
        "admin.reports.period.7d": "Últimos 7 días",
        "admin.reports.period.30d": "Últimos 30 días",
        "admin.reports.period.90d": "Últimos 90 días",
        "admin.reports.period.365d": "Último año",
        "admin.reports.period.all": "Todo el tiempo",

        "admin.reports.stats.total_revenue": "Ingresos Totales",
        "admin.reports.stats.total_sales": "Ventas Totales",
        "admin.reports.stats.pending_commissions": "Comisiones Pendientes",
        "admin.reports.stats.active_vendors": "Vendors Activos",
        "admin.reports.stats.approved_sales": "ventas aprobadas",
        "admin.reports.stats.registered": "registrados",
        "admin.reports.stats.pending": "pendientes",

        "admin.reports.sales_status.title": "Estado de Ventas",
        "admin.reports.sales_status.approved": "Aprobadas",
        "admin.reports.sales_status.pending": "Pendientes",
        "admin.reports.sales_status.rejected": "Rechazadas",

        "admin.reports.commissions.title": "Comisiones",
        "admin.reports.commissions.pending": "Pendientes",
        "admin.reports.commissions.paid": "Pagadas",
        "admin.reports.commissions.count": "comisiones",

        "admin.reports.payments.title": "Solicitudes de Pago",
        "admin.reports.payments.pending": "Pendientes",
        "admin.reports.payments.approved": "Aprobadas",
        "admin.reports.payments.rejected": "Rechazadas",
        "admin.reports.payments.total_approved": "Total aprobado",

        "admin.reports.top_vendors.title": "Top Vendors por Ingresos",
        "admin.reports.top_vendors.subtitle": "Los mejores vendedores del período",
        "admin.reports.top_vendors.sales": "ventas",
        "admin.reports.top_vendors.empty": "No hay datos disponibles",

        "admin.reports.top_products.title": "Productos Más Vendidos",
        "admin.reports.top_products.subtitle": "Productos con más ventas aprobadas",
        "admin.reports.top_products.sales": "ventas",
        "admin.reports.top_products.sku": "SKU:",
        "admin.reports.top_products.empty": "No hay datos disponibles",

        "admin.reports.by_channel.title": "Ventas por Canal",
        "admin.reports.by_channel.subtitle": "Distribución de ventas aprobadas por canal de venta",
        "admin.reports.by_channel.empty": "No hay datos disponibles",

        "admin.reports.monthly_trend.title": "Tendencia Mensual",
        "admin.reports.monthly_trend.subtitle": "Últimos 6 meses de ventas aprobadas",
        "admin.reports.monthly_trend.sales": "ventas",

        "admin.reports.export.title": "Exportar Reportes",
        "admin.reports.export.subtitle": "Descarga los datos en formato CSV para análisis externo",
        "admin.reports.export.sales": "Reporte de Ventas",
        "admin.reports.export.commissions": "Reporte de Comisiones",
        "admin.reports.export.payments": "Reporte de Pagos",
        "admin.reports.export.records": "registros",

        "admin.reports.summary.avg_sale": "Venta Promedio",
        "admin.reports.summary.products": "Productos en Catálogo",
        "admin.reports.summary.approval_rate": "Tasa de Aprobación",
        "admin.reports.summary.total_commissions": "Total Comisiones",

        // Admin - Validation
        "admin.validation.title": "Cola de Validación",
        "admin.validation.subtitle": "Revisa y aprueba las ventas pendientes de validación",
        "admin.validation.pending_badge": "{count} ventas pendientes",
        "admin.validation.empty.title": "No hay ventas pendientes",
        "admin.validation.empty.desc": "Todas las ventas han sido validadas. ¡Excelente trabajo!",
        "admin.validation.card.info_title": "Información de la Venta",
        "admin.validation.card.customer_title": "Información del Cliente",
        "admin.validation.card.vendor": "Vendedor",
        "admin.validation.card.product": "Producto",
        "admin.validation.card.imei": "IMEI",
        "admin.validation.card.price": "Precio",
        "admin.validation.card.customer_name": "Nombre",
        "admin.validation.card.customer_phone": "Teléfono",
        "admin.validation.card.customer_email": "Email",
        "admin.validation.card.view_evidence": "Ver Evidencia",

        // Notifications (Admin & Vendor)
        "notifications.title": "Notificaciones",
        "notifications.subtitle.admin": "Mantente al día con las actualizaciones del sistema",
        "notifications.subtitle.vendor": "Mantente al día con tus ventas y comisiones",
        "notifications.mark_all_read": "Marcar todas como leídas",
        "notifications.stats.total": "Total",
        "notifications.stats.unread": "No leídas",
        "notifications.stats.read": "Leídas",
        "notifications.stats.sales": "Ventas",
        "notifications.stats.approved": "Aprobadas",
        "notifications.stats.commissions": "Comisiones",
        "notifications.recent": "Notificaciones Recientes",
        "notifications.recent.desc.admin": "Últimas actualizaciones y alertas del sistema",
        "notifications.recent.desc.vendor": "Últimas actualizaciones sobre tus ventas y comisiones",
        "notifications.empty.title": "No hay notificaciones",
        "notifications.empty.desc": "No tienes notificaciones en este momento",
        "notifications.badge.new": "Nuevo",
        "notifications.view_details": "Ver detalles",
        "notifications.mark_read": "Marcar como leída",
        "notifications.time.now": "Ahora",
        "notifications.time.minutes": "Hace {minutes}m",
        "notifications.time.hours": "Hace {hours}h",
        "notifications.time.yesterday": "Ayer",
        "notifications.time.days": "Hace {days}d",

        // Common errors/success
        "common.success": "Éxito",
        "common.error": "Error",
        "common.saved": "Guardado correctamente",
        "common.deleted": "Eliminado correctamente",
        "common.updated": "Actualizado correctamente",

        // Admin Dashboard
        "admin.hero.title": "Panel de Administración",
        "admin.hero.subtitle": "Gestiona vendedores, valida ventas y supervisa el rendimiento del sistema CUBOT",

        "admin.stats.active_vendors": "Vendedores Activos",
        "admin.stats.pending_sales": "Ventas Pendientes",
        "admin.stats.month_revenue": "Ingresos del Mes",
        "admin.stats.pending_commissions": "Comisiones Pendientes",

        "admin.actions.manage_vendors.title": "Gestionar Vendedores",
        "admin.actions.manage_vendors.desc": "Administra cuentas de vendedores, revisa KYC y configura permisos",
        "admin.actions.manage_vendors.btn": "Ver Vendedores",

        "admin.actions.validation.title": "Cola de Validación",
        "admin.actions.validation.desc_prefix": "Hay",
        "admin.actions.validation.desc_suffix": "ventas esperando validación",
        "admin.actions.validation.btn": "Validar Ahora",

        "admin.actions.reports.title": "Reportes",
        "admin.actions.reports.desc": "Analiza ventas, comisiones y rendimiento general",
        "admin.actions.reports.btn": "Ver Reportes",
    },
    en: {
        // Common
        "common.dashboard": "Dashboard",
        "common.settings": "Settings",
        "common.profile": "Profile",
        "common.logout": "Log Out",
        "common.notifications": "Notifications",
        "common.welcome": "Welcome back!",
        "common.loading": "Loading...",
        "common.save": "Save",
        "common.cancel": "Cancel",
        "common.view_details": "View Details",
        "common.close": "Close",
        "common.my_account": "My Account",
        "common.app_name": "CUBOT System",
        "common.error.imei_not_found": "IMEI not found in inventory",
        "common.error.imei_verification": "Error verifying IMEI",
        "common.error.upload_evidence": "Sales evidence is required",
        "common.error.generic": "Unexpected error",

        // Vendor Sidebar
        "vendor.nav.dashboard": "Dashboard",
        "vendor.nav.register_sale": "Register Sale",
        "vendor.nav.my_sales": "My Sales",
        "vendor.nav.commissions": "Commissions",
        "vendor.nav.payments": "Payments",
        "vendor.nav.products": "Products",
        "vendor.nav.profile": "Profile",
        "vendor.nav.notifications": "Notifications",

        // Admin Sidebar
        "admin.nav.dashboard": "Dashboard",
        "admin.nav.users": "Users",
        "admin.nav.products": "Products",
        "admin.nav.banks": "Banks",
        "admin.nav.sales": "Sales",
        "admin.nav.validation": "Validation Queue",
        "admin.nav.commissions": "Commissions",
        "admin.nav.payments": "Payments",
        "admin.nav.reports": "Reports",
        "admin.nav.notifications": "Notifications",
        "admin.nav.configuration": "Configuration",

        // Vendor Dashboard
        "vendor.hero.subtitle": "Here is your sales and commissions summary",
        "vendor.stats.total_sales": "Total Sales",
        "vendor.stats.validation": "In Validation",
        "vendor.stats.month_sales": "Monthly Sales",
        "vendor.stats.total_earned": "Total Earned",
        "vendor.stats.pending_commissions": "Pending Commissions",
        "vendor.stats.paid_commissions": "Paid Commissions",

        "vendor.actions.new_sale.title": "Register New Sale",
        "vendor.actions.new_sale.desc": "Fill out the form to register a new CUBOT device sale",
        "vendor.actions.new_sale.btn": "Create Sale",

        "vendor.actions.commissions.title": "My Commissions",
        "vendor.actions.commissions.desc": "Check the status of your commissions and payments",
        "vendor.actions.commissions.btn": "View Commissions",

        // Sale Form
        "vendor.sales.new.page_title": "Register New Sale",
        "vendor.sales.new.subtitle": "Register a new sale with IMEI verification",
        "vendor.sales.new.imei_label": "IMEI (15 digits)",
        "vendor.sales.new.verifying": "Verifying...",
        "vendor.sales.new.imei_verified": "IMEI verified",
        "vendor.sales.new.model": "Model",
        "vendor.sales.new.status": "Status",
        "vendor.sales.new.product_label": "Product",
        "vendor.sales.new.product_not_found_warning": "Note: The verified product ({model}) does not exist in the current catalog.",
        "vendor.sales.new.select_product": "Select a product",
        "vendor.sales.new.channel_label": "Sales Channel",
        "vendor.sales.new.channel.online": "Online",
        "vendor.sales.new.channel.store": "Physical Store",
        "vendor.sales.new.channel.marketplace": "Marketplace",
        "vendor.sales.new.channel.phone": "Phone Sale",
        "vendor.sales.new.date_label": "Sale Date",
        "vendor.sales.new.notes_label": "Notes (Optional)",
        "vendor.sales.new.evidence_label": "Evidence (Photo/PDF)",
        "vendor.sales.new.evidence_hint": "JPG, PNG or PDF. Max 5MB.",
        "vendor.sales.new.submit_btn": "Register Sale",
        "vendor.sales.new.submitting": "Registering...",

        // Vendor Commissions
        "vendor.commissions.title": "My Commissions",
        "vendor.commissions.subtitle": "Track your earnings and commission status",
        "vendor.commissions.pending": "Pending Commissions",
        "vendor.commissions.paid": "Paid Commissions",
        "vendor.commissions.table.sale_id": "Sale ID",
        "vendor.commissions.table.product": "Product",
        "vendor.commissions.table.base_amount": "Base Amount",
        "vendor.commissions.table.commission": "Commission",
        "vendor.commissions.table.status": "Status",
        "vendor.commissions.table.date": "Date",
        "vendor.commissions.empty.title": "No commissions yet",
        "vendor.commissions.empty.desc": "Commissions will appear here after sales are approved",

        // Vendor Payments
        "vendor.payments.title": "Payment History",
        "vendor.payments.subtitle": "View your payment batches and transaction history",
        "vendor.payments.table.batch_id": "Batch ID",
        "vendor.payments.table.commissions": "Commissions",
        "vendor.payments.table.amount": "Amount",
        "vendor.payments.table.status": "Status",
        "vendor.payments.table.date": "Date",
        "vendor.payments.empty.title": "No payment history yet",
        "vendor.payments.empty.desc": "Payment batches will appear here once processed",

        // Vendor Products
        "vendor.products.title": "Product Catalog",
        "vendor.products.subtitle": "Explore available products and their commissions",
        "vendor.products.active": "Active",
        "vendor.products.price": "Price",
        "vendor.products.price_tooltip": "Product sales price",
        "vendor.products.your_commission": "Your Commission",
        "vendor.products.commission_fixed": "Fixed commission per sale",
        "vendor.products.commission_percent": "{percent}% commission on sales price",
        "vendor.products.commission_none": "No commission configured",
        "vendor.products.empty.title": "No products available",
        "vendor.products.empty.desc": "Contact administrator to add products to the catalog",

        // Vendor Profile
        "vendor.profile.title": "My Profile",
        "vendor.profile.subtitle": "Manage your personal information and bank account",
        "vendor.profile.details.vendor_id": "Vendor ID",
        "vendor.profile.details.email": "Email",
        "vendor.profile.details.status": "Status",
        "vendor.profile.details.kyc_status": "KYC Status",
        "vendor.profile.details.id_number": "ID/RNC",
        "vendor.profile.status.active": "Active",
        "vendor.profile.status.suspended": "Suspended",
        "vendor.profile.status.approved": "Approved",
        "vendor.profile.status.rejected": "Rejected",
        "vendor.profile.status.pending": "Pending",

        "vendor.profile.form.title": "Personal Information",
        "vendor.profile.form.desc": "Complete your personal information for verification",
        "vendor.profile.form.full_name": "Full Name",
        "vendor.profile.form.phone": "Phone",
        "vendor.profile.form.country": "Country",
        "vendor.profile.form.address": "Address",
        "vendor.profile.form.city": "City",
        "vendor.profile.form.state": "State/Province",
        "vendor.profile.form.zip": "Postal Code",
        "vendor.profile.form.save": "Save Changes",
        "vendor.profile.form.saving": "Saving...",
        "vendor.profile.form.kyc_alert": "You must complete your ID or RNC for KYC verification.",

        // Vendor Bank Accounts
        "vendor.bank.title": "Bank Accounts",
        "vendor.bank.subtitle": "Manage your bank accounts to receive payments",
        "vendor.bank.add_btn": "Add Bank Account",
        "vendor.bank.form.title": "Add Bank Account",
        "vendor.bank.form.desc": "Select a bank and enter your account details",
        "vendor.bank.form.bank": "Bank",
        "vendor.bank.form.holder": "Account Holder",
        "vendor.bank.form.number": "Account Number",
        "vendor.bank.form.type": "Account Type",
        "vendor.bank.form.primary": "Set as primary account (used for payments)",
        "vendor.bank.form.save": "Save Account",
        "vendor.bank.form.cancel": "Cancel",
        "vendor.bank.empty.title": "No bank accounts configured",
        "vendor.bank.empty.desc": "Add a bank account to receive your commission payments",
        "vendor.bank.verified": "Verified",
        "vendor.bank.pending": "Verification Pending",
        "vendor.bank.set_primary": "Set as Primary",
        "vendor.bank.delete.title": "Delete bank account?",
        "vendor.bank.delete.desc": "This action cannot be undone. The bank account will be permanently removed from your profile.",
        "vendor.bank.delete.btn": "Delete",

        // Vendor Notifications
        "vendor.notifications.title": "Notifications",
        "vendor.notifications.subtitle": "{unread} unread of {total} total",
        "vendor.notifications.mark_all": "Mark all as read",
        "vendor.notifications.mark_read": "Mark as read",
        "vendor.notifications.empty": "No notifications",
        "vendor.notifications.new": "New",

        "vendor.sales.list.title": "My Sales",
        "vendor.sales.list.subtitle": "View and track all your sales",
        "vendor.sales.list.stat.total": "Total Sales",
        "vendor.sales.list.stat.approved": "Approved",
        "vendor.sales.list.stat.pending": "Pending",
        "vendor.sales.list.stat.revenue": "Total Revenue",
        "vendor.sales.list.table.id": "Sale ID",
        "vendor.sales.list.table.product": "Product",
        "vendor.sales.list.table.client": "Client",
        "vendor.sales.list.table.imei": "IMEI",
        "vendor.sales.list.table.price": "Price",
        "vendor.sales.list.table.status": "Status",
        "vendor.sales.list.table.date": "Date",
        "vendor.sales.list.status.approved": "Approved",
        "vendor.sales.list.status.rejected": "Rejected",
        "vendor.sales.list.status.pending": "Pending",
        "vendor.sales.list.empty.title": "No sales registered",
        "vendor.sales.list.empty.desc": "Start registering your first sale from the navigation menu",

        // Admin - Users
        "admin.users.title": "User Management",
        "admin.users.subtitle": "Manage system users",
        "admin.users.search_placeholder": "Search by name, email, vendor ID or phone...",
        "admin.users.tabs.all": "All",
        "admin.users.tabs.admins": "Admin",
        "admin.users.tabs.vendors": "Vendors",
        "admin.users.empty_search": "No users found matching that criteria",
        "admin.users.empty_all": "No users registered",
        "admin.users.role.admin": "Administrator",
        "admin.users.role.validator": "Validator",
        "admin.users.role.finance": "Finance",
        "admin.users.role.vendor": "Vendor",
        "admin.users.status.active": "Active",
        "admin.users.status.suspended": "Suspended",
        "admin.users.kyc.approved": "Approved",
        "admin.users.kyc.rejected": "Rejected",
        "admin.users.kyc.pending": "Pending",
        "admin.users.actions.edit": "Edit",
        "admin.users.actions.suspend": "Suspend",
        "admin.users.actions.activate": "Activate",
        "admin.users.actions.approve": "Approve",
        "admin.users.actions.reject": "Reject",
        "admin.users.actions_label": "Actions",
        "admin.users.dialog.reject_title": "Reject KYC",
        "admin.users.dialog.reject_desc": "Provide a reason for rejecting {name}'s KYC",
        "admin.users.dialog.reject_reason": "Rejection Reason",
        "admin.users.dialog.reject_placeholder": "Ex: Incomplete documents...",
        "admin.users.dialog.cancel": "Cancel",
        "admin.users.dialog.confirm_reject": "Reject KYC",
        "admin.users.registered": "Registered: {date}",
        "admin.users.loading": "Loading users...",

        // Admin - Products
        "admin.products.title": "Products",
        "admin.products.subtitle": "Manage CUBOT product catalog",
        "admin.products.add_button": "Add Product",
        "admin.products.edit_title": "Edit Product",
        "admin.products.add_title": "Add New Product",
        "admin.products.edit_desc": "Update product information",
        "admin.products.add_desc": "Add a new product to the catalog",
        "admin.products.form.sku": "SKU",
        "admin.products.form.sku_tooltip": "Unique product code",
        "admin.products.form.name": "Name",
        "admin.products.form.category": "Category",
        "admin.products.form.price": "Price (RD$)",
        "admin.products.form.price_tooltip": "Product selling price in Dominican Pesos",
        "admin.products.form.commission_label": "Commission",
        "admin.products.form.commission_fixed": "Fixed Amount (RD$)",
        "admin.products.form.commission_fixed_tooltip": "Fixed commission per sale (leave 0 if using percentage)",
        "admin.products.form.commission_percent": "Percentage (%)",
        "admin.products.form.commission_percent_tooltip": "Commission percentage of sales price (leave 0 if using fixed amount)",
        "admin.products.form.stock": "Stock",
        "admin.products.form.active": "Active product (visible to vendors)",
        "admin.products.form.save_loading": "Saving...",
        "admin.products.form.update": "Update Product",
        "admin.products.form.create": "Create Product",
        "admin.products.form.cancel": "Cancel",
        "admin.products.status.active": "Active",
        "admin.products.status.inactive": "Inactive",
        "admin.products.card.category": "Category",
        "admin.products.card.price": "Price",
        "admin.products.card.commission": "Commission",
        "admin.products.card.commission_fixed": "Fixed commission per sale",
        "admin.products.card.commission_percent": "{percent}% commission on price",
        "admin.products.card.commission_none": "No commission configured",
        "admin.products.card.stock": "Stock",
        "admin.products.card.edit_action": "Edit Product",
        "admin.products.empty.title": "No products registered",
        "admin.products.empty.desc": "Add products to the catalog so vendors can sell them",

        // Admin - Banks
        "admin.banks.title": "Bank Management",
        "admin.banks.subtitle": "Configure available banks for vendor payment accounts",
        "admin.banks.add_button": "Add Bank",
        "admin.banks.edit_title": "Edit Bank",
        "admin.banks.add_title": "Add New Bank",
        "admin.banks.edit_desc": "Update bank information",
        "admin.banks.add_desc": "Add a new bank that vendors can use for payments",
        "admin.banks.form.name": "Bank Name",
        "admin.banks.form.code": "Bank Code",
        "admin.banks.form.code_tooltip": "Unique bank code (e.g., BPD, BHD)",
        "admin.banks.form.country": "Country Code",
        "admin.banks.form.format": "Account Number Format",
        "admin.banks.form.format_tooltip": "Format hint for vendors (e.g., '20 digits')",
        "admin.banks.form.active": "Active (visible to vendors)",
        "admin.banks.empty.title": "No banks configured",
        "admin.banks.empty.desc": "Add a bank so vendors can set up their bank accounts",
        "admin.banks.delete_title": "Delete bank?",
        "admin.banks.delete_desc": "This action cannot be undone. The bank will be permanently deleted from the system.",
        "admin.banks.delete_confirm": "Delete",

        // Admin - Sales
        "admin.sales.title": "Sales",
        "admin.sales.subtitle": "Manage and view all system sales",
        "admin.sales.stats.total": "Total Sales",
        "admin.sales.stats.approved": "Approved",
        "admin.sales.stats.pending": "Pending",
        "admin.sales.stats.revenue": "Total Revenue",
        "admin.sales.table.sale_id": "Sale ID",
        "admin.sales.table.vendor": "Vendor",
        "admin.sales.table.product": "Product",
        "admin.sales.table.imei": "IMEI",
        "admin.sales.table.price": "Price",
        "admin.sales.table.status": "Status",
        "admin.sales.table.date": "Date",
        "admin.sales.status.approved": "Approved",
        "admin.sales.status.rejected": "Rejected",
        "admin.sales.status.pending": "Pending",
        "admin.sales.empty.title": "No sales registered",
        "admin.sales.empty.desc": "Sales will appear here when vendors register them",

        // Admin - Reports
        "admin.reports.title": "Reports Center",
        "admin.reports.subtitle": "Complete analysis of your business performance",
        "admin.reports.period.7d": "Last 7 days",
        "admin.reports.period.30d": "Last 30 days",
        "admin.reports.period.90d": "Last 90 days",
        "admin.reports.period.365d": "Last year",
        "admin.reports.period.all": "All time",

        "admin.reports.stats.total_revenue": "Total Revenue",
        "admin.reports.stats.total_sales": "Total Sales",
        "admin.reports.stats.pending_commissions": "Pending Commissions",
        "admin.reports.stats.active_vendors": "Active Vendors",
        "admin.reports.stats.approved_sales": "approved sales",
        "admin.reports.stats.registered": "registered",
        "admin.reports.stats.pending": "pending",

        "admin.reports.sales_status.title": "Sales Status",
        "admin.reports.sales_status.approved": "Approved",
        "admin.reports.sales_status.pending": "Pending",
        "admin.reports.sales_status.rejected": "Rejected",

        "admin.reports.commissions.title": "Commissions",
        "admin.reports.commissions.pending": "Pending",
        "admin.reports.commissions.paid": "Paid",
        "admin.reports.commissions.count": "commissions",

        "admin.reports.payments.title": "Payment Requests",
        "admin.reports.payments.pending": "Pending",
        "admin.reports.payments.approved": "Approved",
        "admin.reports.payments.rejected": "Rejected",
        "admin.reports.payments.total_approved": "Total approved",

        "admin.reports.top_vendors.title": "Top Vendors by Revenue",
        "admin.reports.top_vendors.subtitle": "Best performing vendors in the period",
        "admin.reports.top_vendors.sales": "sales",
        "admin.reports.top_vendors.empty": "No data available",

        "admin.reports.top_products.title": "Top Selling Products",
        "admin.reports.top_products.subtitle": "Products with most approved sales",
        "admin.reports.top_products.sales": "sales",
        "admin.reports.top_products.sku": "SKU:",
        "admin.reports.top_products.empty": "No data available",

        "admin.reports.by_channel.title": "Sales by Channel",
        "admin.reports.by_channel.subtitle": "Distribution of approved sales by channel",
        "admin.reports.by_channel.empty": "No data available",

        "admin.reports.monthly_trend.title": "Monthly Trend",
        "admin.reports.monthly_trend.subtitle": "Last 6 months of approved sales",
        "admin.reports.monthly_trend.sales": "sales",

        "admin.reports.export.title": "Export Reports",
        "admin.reports.export.subtitle": "Download data in CSV format for external analysis",
        "admin.reports.export.sales": "Sales Report",
        "admin.reports.export.commissions": "Commissions Report",
        "admin.reports.export.payments": "Payments Report",
        "admin.reports.export.records": "records",

        "admin.reports.summary.avg_sale": "Average Sale",
        "admin.reports.summary.products": "Products in Catalog",
        "admin.reports.summary.approval_rate": "Approval Rate",
        "admin.reports.summary.total_commissions": "Total Commissions",

        // Admin - Validation
        "admin.validation.title": "Validation Queue",
        "admin.validation.subtitle": "Review and approve pending sales",
        "admin.validation.pending_badge": "{count} pending sales",
        "admin.validation.empty.title": "No pending sales",
        "admin.validation.empty.desc": "All sales have been validated. Great work!",
        "admin.validation.card.info_title": "Sale Information",
        "admin.validation.card.customer_title": "Customer Information",
        "admin.validation.card.vendor": "Vendor",
        "admin.validation.card.product": "Product",
        "admin.validation.card.imei": "IMEI",
        "admin.validation.card.price": "Price",
        "admin.validation.card.customer_name": "Name",
        "admin.validation.card.customer_phone": "Phone",
        "admin.validation.card.customer_email": "Email",
        "admin.validation.card.view_evidence": "View Evidence",

        // Notifications (Admin & Vendor)
        "notifications.title": "Notifications",
        "notifications.subtitle.admin": "Stay up to date with system updates",
        "notifications.subtitle.vendor": "Stay up to date with your sales and commissions",
        "notifications.mark_all_read": "Mark all as read",
        "notifications.stats.total": "Total",
        "notifications.stats.unread": "Unread",
        "notifications.stats.read": "Read",
        "notifications.stats.sales": "Sales",
        "notifications.stats.approved": "Approved",
        "notifications.stats.commissions": "Commissions",
        "notifications.recent": "Recent Notifications",
        "notifications.recent.desc.admin": "Latest system updates and alerts",
        "notifications.recent.desc.vendor": "Latest updates about your sales and commissions",
        "notifications.empty.title": "No notifications",
        "notifications.empty.desc": "You have no notifications at this time",
        "notifications.badge.new": "New",
        "notifications.view_details": "View details",
        "notifications.mark_read": "Mark as read",
        "notifications.time.now": "Now",
        "notifications.time.minutes": "{minutes}m ago",
        "notifications.time.hours": "{hours}h ago",
        "notifications.time.yesterday": "Yesterday",
        "notifications.time.days": "{days}d ago",

        // Common errors/success
        "common.success": "Success",
        "common.error": "Error",
        "common.saved": "Saved successfully",
        "common.deleted": "Deleted successfully",
        "common.updated": "Updated successfully",

        // Admin Dashboard
        "admin.hero.title": "Admin Dashboard",
        "admin.hero.subtitle": "Manage vendors, validate sales, and oversee the CUBOT system performance",

        "admin.stats.active_vendors": "Active Vendors",
        "admin.stats.pending_sales": "Pending Sales",
        "admin.stats.month_revenue": "Monthly Revenue",
        "admin.stats.pending_commissions": "Pending Commissions",

        "admin.actions.manage_vendors.title": "Manage Vendors",
        "admin.actions.manage_vendors.desc": "Manage vendor accounts, review KYC, and configure permissions",
        "admin.actions.manage_vendors.btn": "View Vendors",

        "admin.actions.validation.title": "Validation Queue",
        "admin.actions.validation.desc_prefix": "There are",
        "admin.actions.validation.desc_suffix": "sales waiting for validation",
        "admin.actions.validation.btn": "Validate Now",

        "admin.actions.reports.title": "Reports",
        "admin.actions.reports.desc": "Analyze sales, commissions, and overall performance",
        "admin.actions.reports.btn": "View Reports",
    }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
    // Try to get from localStorage first (client-side only), default to 'es'
    const [language, setLanguage] = useState<Language>("es")

    useEffect(() => {
        const savedLang = localStorage.getItem("app-language") as Language
        if (savedLang && (savedLang === "es" || savedLang === "en")) {
            setLanguage(savedLang)
        }
    }, [])

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang)
        localStorage.setItem("app-language", lang)
    }

    const t = (key: string) => {
        // @ts-ignore
        const translation = translations[language]?.[key]

        if (translation === undefined) {
            if (process.env.NODE_ENV === 'development') {
                console.warn(`[LanguageContext] Missing key: "${key}" in "${language}"`)
            }
            return key
        }
        return translation
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider")
    }
    return context
}
